openapi: 3.0.1
info:
  title: DynamicSequenceRestAPI
  description: API Definition of DynamicSequenceRestAPI
  version: v1
servers:
- url: http://localhost:8290/uol/v1/dynamicSeqApi
paths:
  /:
    post:
      responses:
        default:
          description: Default response
